name: cadpythonsim2
channels:
  - conda-forge
dependencies:
  - pip
  - sundials
  - scikits.odes
  - ipython
  - cadet
  - pip:
      - git+https://github.com/fau-advanced-separations/CADET-Process.git@dev
